defaults:
  - model: bert
  - data: python_v01

log:
  dir: "../resources/logs/"

model_checkpoint:
  dir: "../resources/model_checkpoints/"

tasks: [ "fit" ]

stats:
  dir: "../resources/stats/"

trainer:
  max_epochs: 16
  patience: 3
  min_delta: 0.03
  fast_dev_run: False