defaults:
  - model: bert
  - data: java_v01

log:
  dir: "../resources/logs/"

model_checkpoint:
  dir: "../resources/model_checkpoints/"

tasks: [ "fit" ]

stats:
  dir: "../resources/stats/"

trainer:
  max_epochs: 16
  fast_dev_run: False