defaults:
  - model: CLM
  - data: CodeXGLUE_v01

log:
  dir: "../resources/logs/"

model_checkpoint:
  dir: "../resources/model_checkpoints/"

tasks: [ "fit" ]

stats:
  dir: "../resources/stats/"

rankings:
  dir: "../resources/rankings/"

attentions:
  dir: "../resources/attentions/"
  sample_id: 0

trainer:
  max_epochs: 16
  patience: 7
  min_delta: 0.01
  precision: 16
  fast_dev_run: False