# @package _group_

name: "bert"

desc_encoder: "source.encoder.BertEncoder.BertEncoder"

desc_encoder_hparams:
  architecture: "bert-base-uncased"
  output_attentions: False

code_encoder: "source.encoder.BertEncoder.BertEncoder"

code_encoder_hparams:
  architecture: "bert-base-uncased"
  output_attentions: False

lr: 1e-5
base_lr: 1e-7
max_lr: 1e-3

loss: "source.loss.NPairsLoss.NPairsLoss"
loss_hparams:
  name: "NPairsLoss"

tokenizer:
  architecture: "bert-base-uncased"

predictions:
  path: "../resources/predictions/bert_predictions.pt"