# @package _group_

name: "bert"

x1_encoder: "source.explainer.BertExplainer.BertExplainer"

x1_encoder_hparams:
  architecture: "bert-base-uncased"
  output_attentions: True

x2_encoder: "source.explainer.BertExplainer.BertExplainer"

x2_encoder_hparams:
  architecture: "bert-base-uncased"
  output_attentions: True

lr: 1e-7

loss: "source.loss.NPairsLoss.NPairsLoss"
loss_hparams:
  name: "NPairsLoss"

tokenizer:
  architecture: "bert-base-uncased"

predictions:
  path: "../resources/predictions/bert_predictions.pt"
