# @package _group_

name: "bert"

x1_encoder: "source.encoder.BertEncoder.BertEncoder"

x1_encoder_hparams:
  architecture: "bert-base-uncased"

x2_encoder: "source.encoder.BertEncoder.BertEncoder"

x2_encoder_hparams:
  architecture: "bert-base-uncased"

lr: 1e-7

tokenizer:
  architecture: "bert-base-uncased"

predictions:
  path: "../resources/predictions/bert_predictions.pt"