# @package _group_

name: "CLM"

desc_encoder: "source.encoder.CodeBertEncoder.CodeBertEncoder"
desc_encoder_hparams:
  architecture: "microsoft/codebert-base"
  output_attentions: False

code_encoder: "source.encoder.CodeBertEncoder.CodeBertEncoder"
code_encoder_hparams:
  architecture: "microsoft/codebert-base"
  output_attentions: False

lr: 1e-5
base_lr: 1e-7
max_lr: 1e-3

loss: "source.loss.NPairsLoss.NPairsLoss"
loss_hparams:
  name: "NPairsLoss"

tokenizer:
  architecture: "microsoft/codebert-base"

predictions:
  path: "../resources/predictions/clm_predictions.pt"