# @package _group_

name: "cnn"

desc_encoder: "source.encoder.CNNEncoder.CNNEncoder"

desc_encoder_hparams:
  vocabulary_size: 50000
  representation_size: 768
  out_channels: 4000
  kernel_sizes: [ 2, 3, 5 ]
  sentence_length: 16

code_encoder: "source.encoder.CNNEncoder.CNNEncoder"

code_encoder_hparams:
  vocabulary_size: 50000
  representation_size: 768
  out_channels: 4000
  kernel_sizes: [ 2, 3, 5 ]
  sentence_length: 64

lr: 1e-5
base_lr: 1e-7
max_lr: 1e-3

loss: "source.loss.NPairsLoss.NPairsLoss"
loss_hparams:
  name: "NPairsLoss"

tokenizer:
  architecture: "bert-base-uncased"

predictions:
  path: "../resources/predictions/cnn_predictions.pt"