# @package _group_

name: "cnn"

x1_encoder: "source.encoder.CNNEncoder.CNNEncoder"

x1_encoder_hparams:
  vocabulary_size: 50000
  representation_size: 768
  out_channels: 4000
  kernel_sizes: [ 2, 3, 5 ]
  sentence_length: 16

x2_encoder: "source.encoder.CNNEncoder.CNNEncoder"

x2_encoder_hparams:
  vocabulary_size: 50000
  representation_size: 768
  out_channels: 4000
  kernel_sizes: [ 2, 3, 5 ]
  sentence_length: 128

lr: 1e-7

tokenizer:
  architecture: "bert-base-uncased"

predictions:
  path: "../resources/predictions/cnn_${data.name}_predictions.pt"