# @package _group_

name: "codebert"

x1_encoder: "source.encoder.CodeBertEncoder.CodeBertEncoder"

x1_encoder_hparams:
  architecture: "microsoft/codebert-base"
  output_attentions: False

x2_encoder: "source.encoder.CodeBertEncoder.CodeBertEncoder"

x2_encoder_hparams:
  architecture: "microsoft/codebert-base"
  output_attentions: False

lr: 5e-4

loss: "source.loss.TripletLoss.TripletLoss"
loss_hparams:
  name: "TripletLoss"

tokenizer:
  architecture: "microsoft/codebert-base"

predictions:
  path: "../resources/predictions/codebert_predictions.pt"