# @package _group_

name: "codebert_cls"

desc_encoder: "source.encoder.CodeBertCLSEncoder.CodeBertCLSEncoder"

desc_encoder_hparams:
  architecture: "microsoft/codebert-base"
  output_attentions: False

code_encoder: "source.encoder.CodeBertCLSEncoder.CodeBertCLSEncoder"

code_encoder_hparams:
  architecture: "microsoft/codebert-base"
  output_attentions: False

lr: 1e-5
base_lr: 1e-7
max_lr: 1e-3

loss: "source.loss.TripletLoss.TripletLoss"
loss_hparams:
  name: "TripletLoss"

tokenizer:
  architecture: "microsoft/codebert-base"

predictions:
  path: "../resources/predictions/codebert_cls_predictions.pt"