# @package _group_

name: "codebert_cls"

x1_encoder: "source.encoder.CodeBertCLSEncoder.CodeBertCLSEncoder"

x1_encoder_hparams:
  architecture: "microsoft/codebert-base"
  output_attentions: False

x2_encoder: "source.encoder.CodeBertCLSEncoder.CodeBertCLSEncoder"

x2_encoder_hparams:
  architecture: "microsoft/codebert-base"
  output_attentions: False

lr: 1e-7

loss: "source.loss.TripletLoss.TripletLoss"
loss_hparams:
  name: "TripletLoss"

tokenizer:
  architecture: "microsoft/codebert-base"

predictions:
  path: "../resources/predictions/codebert_cls_predictions.pt"