# @package _group_

name: "gpt"

x1_encoder: "source.encoder.GPTEncoder.GPTEncoder"

x1_encoder_hparams:
  architecture: "gpt2"
  output_attentions: False

x2_encoder: "source.encoder.GPTEncoder.GPTEncoder"

x2_encoder_hparams:
  architecture: "gpt2"
  output_attentions: False

lr: 1e-7

loss: "source.loss.NPairsLoss.NPairsLoss"
loss_hparams:
  name: "NPairsLoss"

tokenizer:
  architecture: "gpt2"

predictions:
  path: "../resources/predictions/gpt_predictions.pt"