# @package _group_

name: "gru"

desc_encoder: "source.encoder.GRUEncoder.GRUEncoder"

desc_encoder_hparams:
  vocabulary_size: 50000
  representation_size: 768
  hidden_size: 768

code_encoder: "source.encoder.GRUEncoder.GRUEncoder"

code_encoder_hparams:
  vocabulary_size: 50000
  representation_size: 768
  hidden_size: 768

lr: 1e-7

loss: "source.loss.NPairsLoss.NPairsLoss"
loss_hparams:
  name: "NPairsLoss"

tokenizer:
  architecture: "bert-base-uncased"

predictions:
  path: "../resources/predictions/gru_predictions.pt"