# @package _group_

name: "lstm"

x1_encoder: "source.encoder.LSTMEncoder.LSTMEncoder"

x1_encoder_hparams:
  vocabulary_size: 50000
  representation_size: 768
  hidden_size: 768

x2_encoder: "source.encoder.LSTMEncoder.LSTMEncoder"

x2_encoder_hparams:
  vocabulary_size: 50000
  representation_size: 768
  hidden_size: 768

lr: 1e-7

loss: "source.loss.TripletLoss.TripletLoss"
loss_hparams:
  name: "TripletLoss"

tokenizer:
  architecture: "bert-base-uncased"

predictions:
  path: "../resources/predictions/lstm_predictions.pt"