# @package _group_

name: "mclm"

x1_encoder: "source.encoder.MCLMEncoder.MCLMEncoder"

x1_encoder_hparams:
  architecture: "microsoft/codebert-base"
  output_attentions: False

x2_encoder: "source.encoder.MCLMEncoder.MCLMEncoder"

x2_encoder_hparams:
  architecture: "microsoft/codebert-base"
  output_attentions: False

lr: 1e-7

loss: "source.loss.NPairsLoss.NPairsLoss"
loss_hparams:
  name: "NPairsLoss"

tokenizer:
  architecture: "microsoft/codebert-base"

predictions:
  path: "../resources/predictions/mclm_predictions.pt"