# @package group

name: "nbow"

x1_encoder: "source.encoder.NBOWEncoder.NBOWEncoder"

x1_encoder_hparams:
  vocabulary_size: 50000
  representation_size: 768

lr: 1e-7

x2_encoder: "source.encoder.NBOWEncoder.NBOWEncoder"

x2_encoder_hparams:
  vocabulary_size: 50000
  representation_size: 768

tokenizer:
  architecture: "bert-base-uncased"

predictions:
  path: "../resources/predictions/nbow_${data.name}_predictions.pt"