# @package _group_

name: "rnn"

x1_encoder: "source.encoder.RNNEncoder.RNNEncoder"

x1_encoder_hparams:
  vocabulary_size: 50000
  representation_size: 768
  hidden_size: 768

lr: 1e-7

x2_encoder: "source.encoder.RNNEncoder.RNNEncoder"

x2_encoder_hparams:
  vocabulary_size: 50000
  representation_size: 768
  hidden_size: 768

tokenizer:
  architecture: "bert-base-uncased"

predictions:
  path: "../resources/predictions/rnn_predictions.pt"