# @package _group_

name: "roberta"

desc_encoder: "source.encoder.RoBERTaEncoder.RoBERTaEncoder"

desc_encoder_hparams:
  architecture: "roberta-base"

code_encoder: "source.encoder.RoBERTaEncoder.RoBERTaEncoder"

code_encoder_hparams:
  architecture: "roberta-base"

tokenizer:
  architecture: "roberta-base"

lr: 1e-5
base_lr: 1e-7
max_lr: 1e-3

loss: "source.loss.NPairsLoss.NPairsLoss"
loss_hparams:
  name: "NPairsLoss"

predictions:
  path: "../resources/predictions/roberta_predictions.pt"