# @package _group_

name: "roclm"

desc_encoder: "source.encoder.RoBERTaEncoder.RoBERTaEncoder"

desc_encoder_hparams:
  architecture: "roberta-base"
  output_attentions: False

code_encoder: "source.encoder.CLMEncoder.CLMEncoder"

code_encoder_hparams:
  architecture: "microsoft/codebert-base"
  output_attentions: False

lr: 1e-5
base_lr: 1e-7
max_lr: 1e-3

loss: "source.loss.NPairsLoss.NPairsLoss"
loss_hparams:
  name: "NPairsLoss"

tokenizer:
  architecture: "microsoft/codebert-base"

predictions:
  path: "../resources/predictions/roclm_predictions.pt"