# @package _group_

name: "xlnet"

desc_encoder: "source.encoder.XLNetEncoder.XLNetEncoder"

desc_encoder_hparams:
  architecture: "xlnet-base-cased"
  output_attentions: False

code_encoder: "source.encoder.XLNetEncoder.XLNetEncoder"

code_encoder_hparams:
  architecture: "xlnet-base-cased"
  output_attentions: False

lr: 1e-5
base_lr: 1e-7
max_lr: 1e-3

loss: "source.loss.NPairsLoss.NPairsLoss"
loss_hparams:
  name: "NPairsLoss"

tokenizer:
  architecture: "xlnet-base-cased"

predictions:
  path: "../resources/predictions/xlnet_predictions.pt"